guacsec/trustify-ui

- crate/build.rs
Resolves https://github.com/trustification/trustify-ui/issues/19 and https://github.com/trustification/trustify-ui/issues/16
The UI is always build in prod mode (minified and compressed JS files).
If we want the UI to be seen in dev mode, then we have the `npm run start:dev` which is used for developers to start the UI
> Remove --dev param from the rust crate

- .github/workflows/tag-dist.yaml
- crate/build.rs
I think this should end up creating `static-${ref}` tags like `static-main` tags in the repo which will contain the built dist dir.  If this does work, maybe we can change the crate to just use the existing dist files instead of doing a build?
> ci: attempt to check in the CI build of the dist dir.

- client/src/app/api/models.ts
- client/src/app/pages/advisory-list/advisory-list.tsx
- client/src/app/pages/importer-list/importer-list.tsx
- client/src/mocks/stub-new-work/advisories.ts
- https://github.com/trustification/trustify/issues/277 Has been resolved so I am applying the severity to the advisory list table
- I have discovered a bug and reported it accordingly on https://github.com/trustification/trustify/issues/372
- https://github.com/trustification/trustify/issues/278 has been also resolved so I am removing the "yellow" span label
> Add average severity to advisory list

- client/src/app/axios-config/apiInit.ts
Fixes: https://github.com/trustification/trustify-ui/issues/40
If the access token sent to the backend is rejected with 401 then:
- Try to refresh the token
- If the token cannot be refreshed, then redirect to login page
> Handle 401 token errors

- client/src/app/dayjs.ts
- client/src/app/pages/advisory-details/vulnerabilities.tsx
- client/src/app/pages/importer-list/importer-list.tsx
- client/src/app/pages/vulnerability-details/vulnerability-details.tsx
- client/src/app/utils/utils.ts
- client/src/index.tsx
Add /src/app/dayjs.ts with common options
Add UTC time to importers 
Add `formatDateTime` function
Fix https://github.com/trustification/trustify-ui/issues/68
> Fix: UTC time to active importers

- client/src/app/api/models.ts
- client/src/app/pages/vulnerability-details/advisories-by-vulnerability.tsx
- client/src/app/pages/vulnerability-details/packages-by-vulnerability.tsx
- client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
- client/src/app/pages/vulnerability-details/vulnerability-details.tsx
Based on https://github.com/trustification/trustify/issues/462
We are supposed to see data in the table below 
The current problem is that neither me nor the backend guys were able to make the `advisories.statuses.affected` data appear.
> feat: Packages within Vulnerabilities detail page

- client/src/app/api/models.ts
- client/src/app/components/LoadingWrapper.tsx
- client/src/app/pages/package-details/package-details.tsx
- client/src/app/pages/package-details/vulnerabilities-by-package.tsx
- client/src/app/queries/packages.ts
Fix https://github.com/trustification/trustify/issues/461 and https://github.com/trustification/trustify/issues/412 partially
- The current model is returning multiple duplicate data reported at https://github.com/trustification/trustify/issues/461
- For each vulnerability we still don't know its severity
> feat: add vulnerabilities by package

- crate/Cargo.toml
- crate/src/lib.rs
Instead of using zero as the timestamp, use the actual timestamp. This should fix the issue of a stale page, when updating the UI. In that case the index page is not fetched, and it tries to load the old resources with the (no longer existing) cache busting markers. Resulting in a 404, and resulting in a blank page.
Also, report error through result
Instead of rendering one error into the page and reporting the others through a panic, report all through a result.
> fix: Fix stale index page by reporting the timestamp.

- client/src/app/api/models.ts
- client/src/app/pages/sbom-details/overview.tsx
- client/src/app/pages/sbom-details/sbom-details.tsx
- client/src/app/pages/sbom-list/sbom-list.tsx
- client/src/app/pages/vulnerability-details/related-sboms.tsx
- client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
Based on https://github.com/trustification/trustify/issues/284#issuecomment-2193993777
I don't really think this is the way of showing data, but at this point I have no clue how to render the `described_by` field. So I am just rendering it to have something to show and then on a future iteration let UX and PM decide how useful/correct the `described_by` data is  and how to render it.
> feat: add sbom described_by

- client/package.json
- client/src/app/hooks/useUpload.ts
- client/src/app/pages/advisory-list/advisory-list.tsx
- client/src/app/pages/sbom-list/sbom-list.tsx
- client/src/app/utils/type-utils.ts
- package-lock.json
- server/package.json
Address 7 vulnerabilities (4 moderate, 3 high) 
- Bump axios to 1.7.2 and address type change for `AxiosRequestConfig`
- Bump ejs to 3.1.10
- Bump express to 4.19.2
- Used `npm audit fix --ignore-scripts`
> Fix: Bump packages to resolve packages vulnerabilities

- client/src/app/api/models.ts
- client/src/app/pages/importer-list/importer-list.tsx
This will also be fixed on the backend side.
> fix: correct field name

- client/src/app/pages/importer-list/components/importer-form.tsx
- client/src/app/pages/importer-list/importer-list.tsx
When editing an importer the type should be the existing one and on creation the type will be empty (null).
fix https://github.com/trustification/trustify-ui/issues/100
> fix: Importer type - new vs edit

- client/src/app/pages/importer-list/importer-list.tsx
Remove unnecessary sorting importers reports when managing the items in `useLocalTableControls`.
Although sorting out reports using only the `startDate` should be enough and using both start and end dates are likely to break the original order therefore as the API is already providing the reports in timely fashioned order then there is no need to reorder the items.
Before: 
After: 
Fix https://github.com/trustification/trustify-ui/issues/104
> fix: Importer reports: use API order

- client/src/app/api/models.ts
- client/src/app/pages/package-details/vulnerabilities-by-package.tsx
- client/src/app/pages/vulnerability-details/packages-by-vulnerability.tsx
- client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
To make the code easier to understand lets avoid nesting object definitions.
Using a non primitive type (or through an interface) helps for code clarity and not necessarily only when that nested definition is reused.
In both cases a meaningful name is desirable as much as possible (but not always an easy find).
Also replace `StatusType` type to `SbomStatus` because it offers a more description of the object and avoid overloading the name with its type.
> Avoid nesting objects definition

- client/src/app/pages/advisory-list/advisory-list.tsx
Rendering the source of Advisory files when they are big frozen the browser. Watch the second 33 of the following recording.
We can verify it uploading this CSAF file (4MB). 
[CVE-2024-24783.json](https://github.com/user-attachments/files/16430134/CVE-2024-24783.json)
https://github.com/user-attachments/assets/310925d8-7fc4-4dc0-b0a7-94bdbbf6e030
- Removing the "Source viewer" from the advisory list will avoid this issues.
- Surprisingly the "Source viewer" works fine inside the tab (so leaving it there unless we find out it is a bad idea)
> fix: remove "view source" in modal, from advisory list

- .github/workflows/tag-dist.yaml
Right now we have the issue that the tag points to a dangling commit, as the commit itself doesn't belong to a branch. Once a new tag is pushed, that commit might go away. This leads to failing local builds and failing CI release builds.
The goal of this change is to create a "publish" branch per branch that we publish, keeping the commits there.
> ci: create a "publish" branch, keeping published commits

- client/src/app/Routes.tsx
- client/src/app/queries/advisories.ts
- client/src/app/queries/importers.ts
- client/src/app/queries/organizations.ts
- client/src/app/queries/packages.ts
- client/src/app/queries/products.ts
- client/src/app/queries/sboms.ts
- client/src/app/queries/vulnerabilities.ts
This simplifies the queries/*.ts function signatures and implementations.
This also provides a better error messages during dev.
If you use an invalid route param arg, UI screen only displays an empty result at the current time.  Example: 
With this change, if you use an invalid route param, you will see:
> cleanup: useRouteParams now returns string or throws error

- client/src/app/hooks/table-controls/filtering/getFilterHubRequestParams.ts
Make code safer and avoid potential undefined values to be set to the set of filter values set in the table-controls
> fix: do not allow undefined values to be push to filterValues

- client/src/app/Routes.tsx
- client/src/app/layout/sidebar.tsx
The next version of RHTPA won't include PRODUCTS as it is out of scope for the next official release. So removing it until the time to have it comes
> Remove product page&routing as it won't be included in the release of rhtpa

- client/src/app/components/SbomsByPackageCount.tsx
- client/src/app/pages/package-list/package-context.tsx
- client/src/app/pages/package-list/package-table.tsx
Fixes https://github.com/trustification/trustify-ui/issues/170
- Align the correct columns according to  the spreadsheet shared in the Issue attached to this PR
Some work is still outstanding but should not necessarily block this PR.
- Here is an issue I created for following limitations with SORTING https://github.com/trustification/trustify/issues/888
- Another Issue for the SBOM Count https://github.com/trustification/trustify/issues/889
> Package List - V1 Parity

- client/src/app/pages/advisory-details/vulnerabilities.tsx
- client/src/app/pages/sbom-details/vulnerabilities-by-sbom.tsx
- client/src/app/pages/vulnerability-details/advisories-by-vulnerability.tsx
- client/src/app/pages/vulnerability-list/vulnerability-context.tsx
- client/src/app/pages/vulnerability-list/vulnerability-table.tsx
relates to #171 
Still need to add the Published column ~~and check the CVSS column~~.
> feat(cve): update columns

- client/src/app/hooks/table-controls/filtering/useFilterState.ts
- client/src/app/pages/importer-list/components/importer-form.tsx
- common/package.json
- common/src/proxies.ts
- package-lock.json
- server/package.json
The PR https://github.com/trustification/trustify-ui/pull/99 upgraded http-proxy-middleware to version 3 as a consecuence the container image does not work anylonger.
How to see the error:
- Start the backend with the instructions from https://github.com/trustification/trustify 
```shell
cargo run --bin trustd
```
- The following command was extracted from the backend README:
```shell
podman run --network="host" --pull=always \
-e TRUSTIFY_API_URL=http://localhost:8080 \
-e OIDC_CLIENT_ID=frontend \
-e OIDC_SERVER_URL=http://localhost:8090/realms/trustify \
-e ANALYTICS_ENABLED=false \
-e PORT=3000 \
-p 3000:3000 \
ghcr.io/trustification/trustify-ui:latest
```
- Open the UI at http://localhost:3000
An error will appear in the ui container and the UI can not connect to the backend.
This PR …
> fix: rever http-proxy-middleware version and make sure the container works with it

- client/src/app/pages/vulnerability-details/overview.tsx
- client/src/app/pages/vulnerability-details/vulnerability-details.tsx
implements #190 
- Rearrange properties in `Overview` component to reflect v1
- Adapt labels in tables according to [this guide](https://docs.google.com/spreadsheets/d/1mhBd3-UYvSANIXwRPDrCdGplN7cq5rQPJhIywo5mcDY/edit?gid=1088076328#gid=1088076328)
- Move tabs + `Overview` into dedicated area outside of `DetailPage`
- Remove `DetailPage`, as we are no longer using those breadcrumbs, built-in tabs, or actions
- Keep or ditch the "Related Products" tab from v1
- Keep or ditch "Packages" tab from v2
- Do we want to show properties not shown (available?) in v1 ("non-normative", "CWE", "withdrawn", "released")?
- What happened to the "Reserved" property in v1, was that renamed? maybe to one of the above?
> feat(cve): details page v1 parity

- .eslintrc.cjs
- .gitignore
- .storybook/main.ts
- .storybook/preview.ts
- client/.gitignore
- client/src/app/pages/home/home.stories.tsx
- client/src/app/pages/vulnerability-details/overview.stories.tsx
- client/src/app/pages/vulnerability-details/vulnerability-details.stories.tsx
- package-lock.json
- package.json
implements #193 
Docs view for a UI component:
Changes:
- Adds Storybook + its own Webpack config
- Adds a couple of TPA-specific stories, but very basic
TBD:
- The setup and directories. Still trying to come up with a good way to divide the stories, maybe I'll separate them into Pages & Components, as opposed to "entities"
- Need to set up mocking for connected components, to be able to better represent pages
PR incoming for setting up Chromatic and Storybook with CI/CD.
> feat: add storybook

- .github/workflows/ci-repo.yaml
- .github/workflows/storybook-pr-build.yaml
- .github/workflows/storybook-pr-deploy.yaml
- .github/workflows/storybook.yaml
- Add `storybook-pr-build.yaml` to build storybook each time any story is touched. If no story is touched then it won't be triggered.
- Add `storybook-pr-deploy.yaml` to deploy a preview of Storybook each time a story is touched in a PR. It will also add a comment to the PR indicating to the user where he can pre visualize his changes. Here is an example of how it will work https://github.com/carlosthe19916/trustify-ui/pull/10
- Add `storybook.yaml` to deploy Storybook in Github page. It will only deploy what is in the main branch. This is how it will look like once merge https://carlosthe19916.github.io/trustify-ui/ . I tested it in my own fork.
Requirements:
- We are using surge.sh to pre visualize PR stories. Therefore we need `SURGE_TOKEN` which is already set in the Organization.
- …
> ci: Storybook visualization

- client/src/app/Routes.tsx
- client/src/app/layout/sidebar.tsx
- client/src/app/pages/advisory-list/advisory-context.tsx
- client/src/app/pages/advisory-list/advisory-list.tsx
- client/src/app/pages/advisory-list/advisory-table.tsx
- client/src/app/pages/advisory-list/advisory-toolbar.tsx
- client/src/app/pages/advisory-list/index.ts
- client/src/app/pages/search/search-context.tsx
- client/src/app/pages/search/search.tsx
- client/src/app/queries/advisories.ts
Fixes: https://github.com/trustification/trustify-ui/issues/213
During yesterday's call, PM and Engineering Manager agreed that we need to also have parity with the Advisories pages.
This PR is adding Advisory list page
> feat: add advisory list

- client/src/app/pages/advisory-list/advisory-context.tsx
- client/src/app/pages/advisory-list/advisory-table.tsx
The issue https://github.com/trustification/trustify/issues/967 is saying that the "revision" column from v1 should be the `modified` field of an advisory.
This PR is adding the "modified" field as a "Revision" Column in the table.
Also making the column sortable.
> feat: Advisory List - Revision Column added

- client/src/app/Routes.tsx
- client/src/app/pages/advisory-details/advisory-details.tsx
- client/src/app/pages/advisory-details/index.ts
- client/src/app/pages/advisory-details/overview.tsx
- client/src/app/pages/advisory-details/vulnerabilities-by-advisory.tsx
- package-lock.json
fix: https://github.com/trustification/trustify-ui/issues/214
This PR adds the Advisory Details page.
There are some missing properties that V2 does not include but we can do it in a separate PR. I'd like this PR to be the skeleton of any additional properties we might add in the future.
> feat: add advisory-details page

- client/src/app/pages/vulnerability-details/advisories-by-vulnerability.stories.tsx
- client/src/app/pages/vulnerability-details/advisories-by-vulnerability.tsx
- client/src/app/pages/vulnerability-details/overview.tsx
- client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
- client/src/app/pages/vulnerability-details/vulnerability-details.tsx
This PR is for v1 parity of the CVE detail page, relates to #190 .
https://trust.rhcloud.com/cve/content/CVE-2023-1664
> chore(cve): v1 parity detail enhancements

- .storybook/main.ts
- .storybook/preview.tsx
- client/package.json
- client/src/app/pages/vulnerability-list/vulnerability-list.stories.tsx
- client/src/app/pages/vulnerability-list/vulnerability-table.stories.tsx
- client/src/app/pages/vulnerability-list/vulnerability-toolbar.stories.tsx
- client/src/mocks/browser.ts
- client/src/mocks/stub-new-work/index.ts
- package-lock.json
- package.json
- public/mockServiceWorker.js
This PR paves the way for other connected components or pages that require network requests from within Storybook. The long-term goal here is to have a platform we can iterate on and ideate with, without modifying the main UI.
- Add support for msw in Storybook, migrate existing msw 1.x to 2.x
- Mock requests for vulnerability list page in Storybook
- Fix broken stories by wrapping in the appropriate provider and/or providing data as expected
- Remove `storybook/onboarding` add-on, as it's no longer necessary
Relates to #193
> fix(storybook): add msw to mock network requests, fix existing stories

- client/src/app/components/OidcProvider.tsx
Fixes: https://github.com/trustification/trustify-ui/issues/33, #245 
This PR will render an error rather than retrying, indefinetly, to pull the OIDC configuration.
> fix: stop the infinite loop when the OIDC server does not respond as expected

- client/src/app/pages/sbom-details/overview.tsx
Fixes: https://github.com/trustification/trustify-ui/issues/89
This PR adds the "Package" section to the SBOM Details Page / Info Tab. See image below.
> fix: add package section to SBOM Details-Info Tab

- client/src/app/App.css
- client/src/app/pages/upload/components/upload-file.tsx
fixes: https://github.com/trustification/trustify-ui/issues/265
Currently Patternfly React does not allow to use the BLUE color for the "In progress" bars. I reported this bug in their repository https://github.com/patternfly/patternfly-react/issues/11276 but that will take time to be fixed.
@jcrossley3 the main reason of the issue was that although a file cam be 100% sent to the server, the server can still take time to process the file although the file has been fully sent already. This PR should make the Progress Bar always BLUE unless the server gives a response. It also adds a helper text to explain that.
https://github.com/user-attachments/assets/d5a02a23-ee0c-41d1-98a3-c0205473bb9b
> fix: upload progress does not have blue color. Force it

- client/src/app/pages/home/components/MonitoringSection.tsx
Fixes: https://github.com/trustification/trustify-ui/issues/268
The Dashboard Page has a Barchart whose Y vertical axis render the last 10 SBOMs. If there is not at least 1 SBOM then it is imposible for the chart to guess what to render in the Y axis therefore this PR will render an empty state when no sboms are available
> fix: dashboard - avoid rendering barchart when no sboms are available

- client/src/app/components/VulnerabilityStatusLabel.tsx
- client/src/app/hooks/domain-controls/useSbomsOfVulnerability.ts
- client/src/app/hooks/domain-controls/useVulnerabilitiesOfSbom.ts
- client/src/app/pages/vulnerability-details/packages-by-vulnerability.tsx
- client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
- client/src/app/pages/vulnerability-list/components/SbomsCount.stories.tsx
- client/src/app/pages/vulnerability-list/components/SbomsCount.tsx
Thanks to this https://github.com/trustification/trustify/issues/1006 we can reduce the number of calls done to the backend when we are at the CVEs details page:
BEFORE:
- For each SBOM found in the Vulnerability/CVE we fetch the SBOM.
AFTER
- We do not need to fetch each SBOM as the original request has everything we need.
> fix: reduce calls to backend on vulnerabilities page

- client/src/app/pages/search/components/SearchTabs.tsx
- client/src/app/pages/search/search.tsx
Fixes https://github.com/trustification/trustify-ui/issues/280
- `vulnerabilityTotalCount` was set instead of `advisoryTotalCount` => fixed that
- Just order the variable declarations in the same order in which the tabs are rendered. This has zero effect on the final result but just wanted it to help me to better read the code in the future
> fix: Search Page wrong advisories count

- client/src/app/pages/home/components/MonitoringSection.tsx
- client/src/app/utils/utils.ts
The code in the main branch fetches the SBOMs and Advisories based on their "published" data which is wrong and it was just a placeholder while we wait for https://github.com/trustification/trustify/issues/1077 to be implemented in the backend.
Now that we can sort SBOM/Advisory by `ingested` we can use it to get the last SBOMs and advisories ingested into the system to properly populate the dashboard.
> fix: dashboard to use ingested time to fetch last sbom/advisory

- client/openapi/trustd.yaml
- client/src/app/client/schemas.gen.ts
- client/src/app/client/types.gen.ts
- client/src/app/hooks/domain-controls/useSbomsOfVulnerability.ts
- client/src/app/pages/vulnerability-details/advisories-by-vulnerability.stories.tsx
- client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
Matching changes done in the backend at https://github.com/trustification/trustify/pull/1098
Now we should be able to render the packages within an SBOM when we are in the VUlnerabilities page Details. See image below... it should also be consistent with V1 as V1 has exactly the same expanded area on the "Dependencies column"
> feat: add Vuln Details -> Related SBOMBs -> dependencies list

- client/src/app/pages/importer-list/importer-list.tsx
- Changed the `Output` header to be `Status` to better reflect the information it gives
- Slightly changed the columns' widths to let `Number of items` and `Duration` to have a little bit more space (check screenshot)
> Importer list: 'Status' header replaces 'Output'

- client/src/app/pages/package-details/package-details.tsx
- client/src/app/pages/package-details/sboms-by-package.tsx
- client/src/app/queries/sboms.ts
In response to https://github.com/trustification/trustify/issues/1163
The UI now should use the QueryParam `purl` to get the sboms related to a package
> fix: sbom's packages view

- .github/workflows/backport.yaml
solves https://github.com/trustification/trustify-ui/issues/336
Any PR that needs to be backported to the branch release/0.2.z need to add the label "backport release/0.2.z" manually, then a backport PR should be created by gh actions.
I tested it in my own account see:
- https://github.com/carlosthe19916/trustify-ui/pull/22 is a PR opened from a forked repository
- a backport https://github.com/carlosthe19916/trustify-ui/pull/23 was created automatically
> ci: add backport action

- client/src/app/pages/sbom-details/vulnerabilities-by-sbom.tsx
Fixes https://github.com/trustification/trustify-ui/issues/369
The SBOM Details page / Vulnerability Tab contains duplicate packages. This PR just filters them out.
To compare the main Results vs this PR results we can import the 2 files attached to the issue https://github.com/trustification/trustify-ui/issues/369 and then go to the "The SBOM Details page / Vulnerability Tab"
This is what I see with this PR 
Note that there are 4 libnghttp2 but all of them belong to a different purl (you can see they have different architecture)
> :sparkles: sbom details page - filter out duplicate packages

- client/src/app/pages/importer-list/importer-list.tsx
Related to #149
As expressed at https://github.com/trustification/trustify-ui/issues/149 , users find difficult to see the importers when they are too many.
This PR adds a filter to the importers table so users can define which status of importers they want to see.
https://github.com/user-attachments/assets/f5cbf1b4-d47f-41ab-bdec-4f693e9dd659
> further enhancements will be needed like the one proposed at https://github.com/trustification/trustify-ui/issues/149#issuecomment-2657181396 . But they can come in PR chunks and iterate over it.
> :sparkles:  add importer filters

- .github/workflows/pr-checks.yml
- CONTRIBUTING.md
- README.md
Recently https://github.com/trustification/release-tools/ added a set of reusable action mainly inspired in the automation used at https://github.com/konveyor/ 
This PR setup a PR title verification for each PR so appropriate titles are always set. This will help to create accurate release notes when we start creating tags/releases.
> :seedling:  setup PR title verification

- client/src/index.tsx
It has been reported, internally, that some dependencies are being part of the final minimized bundles. E.g.
- If in the current main branch we execute `npm run build` and then `grep -r "myjino" client/dist/` we will see some results
- With the current PR we will avoid dependencies comming from `mocks/browser` being injected in the final bundles
We are not using the mocks/browser anyway. And it was originally intended to speed up the very first phase of development in the UI 1 year ago (when there was not backend therefore some mock api was needed to progress the UI).
> :seedling:  remove mocks/browser from index.tsx

- client/src/app/pages/advisory-list/advisory-context.tsx
- client/src/app/pages/sbom-list/sbom-context.tsx
- client/src/app/pages/vulnerability-list/vulnerability-context.tsx
Fixes https://github.com/trustification/trustify-ui/issues/116
Set default sorting to always see the latest entities in the table.
- Advisory table sorted by "modified" date by default
- Sbom table sorted by "published" date by default
- Vulnerability sorted by "published" date by default
> :sparkles: Set default sorting to main tables

- client/src/app/Constants.ts
- client/src/app/pages/importer-list/importer-list.tsx
- client/src/app/pages/search/components/SearchMenu.tsx
- client/src/app/queries/advisories.ts
- client/src/app/queries/importers.ts
- client/src/app/queries/packages.ts
- client/src/app/queries/sboms.ts
- client/src/app/queries/vulnerabilities.ts
Fixes: https://github.com/trustification/trustify-ui/issues/325
Removes all the re-fetch logic with the exception of the Importers as we still need to follow the progress of an importer
- Moves the fetch interval value to a single place (Contants)
- This way we can change the intervals at one shot in a single place
> :sparkles: Stop fetching data every X seconds and do it only when requested 

- client/openapi/trustd.yaml
- client/src/app/api/rest.ts
- client/src/app/hooks/domain-controls/useDownload.ts
- client/src/app/pages/sbom-details/sbom-details.tsx
- client/src/app/pages/sbom-list/sbom-table.tsx
- client/src/app/utils/utils.ts
UI counter part of https://github.com/trustification/trustify/pull/1331
This add UI compatibility with V1 UI in terms of having buttons to download the License report for each SBOM
Setting this PR as a Draft as the backend PR has not been merged yet.
Note: This PR requires UI Tests PR: 33
https://github.com/trustification/trustify-tests/pull/33 for the Global Tests to pass
> :sparkles: Add download license report buttons

- client/src/app/pages/sbom-details/packages-by-sbom.tsx
The namespace should be rendered only if it is different than undefined.
Before
After
> :bug: SBOM/Package table renders 'undefined' if namespace doesn't exist

- client/src/app/pages/search/components/SearchTabs.tsx
While doing the massive recent changes to apply the linting rules of Biome, this unwanted line has been introduced
> :bug:  searchtabs filterCategories being hardcoded

- client/src/app/components/TdWithFocusStatus.tsx
- client/src/app/pages/advisory-details/vulnerabilities-by-advisory.tsx
- client/src/app/pages/advisory-list/advisory-table.tsx
- client/src/app/pages/package-details/vulnerabilities-by-package.tsx
- client/src/app/pages/sbom-details/packages-by-sbom.tsx
- client/src/app/pages/sbom-details/vulnerabilities-by-sbom.tsx
- client/src/app/pages/sbom-list/sbom-table.tsx
- client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
- client/src/app/pages/vulnerability-list/vulnerability-table.tsx
Resolves: https://github.com/trustification/trustify-ui/issues/422
- Added the "truncate" modifier to some columns "td". It was easy, just to add `modifier=truncate`
- If a column renders another component that is not a String, then `modifier=truncate` won't work. So following the docs from https://v5-archive.patternfly.org/components/table#modifiers-with-table-text . I created the Component `TdWithFocusStatus` and apply tooltips for those special columns
> :sparkles: add table tooltips

- client/src/app/pages/search/components/SearchTabs.tsx
- client/src/app/pages/search/search.tsx
Resolves https://github.com/trustification/trustify-ui/issues/352
The Search page now has Spinners on the Tabs
> :sparkles: Add Spinner to Search Page Tabs

- client/src/app/pages/advisory-details/vulnerabilities-by-advisory.tsx
- client/src/app/pages/advisory-list/advisory-table.tsx
- client/src/app/pages/package-details/sboms-by-package.tsx
- client/src/app/pages/package-details/vulnerabilities-by-package.tsx
- client/src/app/pages/package-list/package-table.tsx
- client/src/app/pages/sbom-details/vulnerabilities-by-sbom.tsx
- client/src/app/pages/sbom-list/sbom-table.tsx
- client/src/app/pages/vulnerability-details/advisories-by-vulnerability.tsx
- client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
- client/src/app/pages/vulnerability-list/vulnerability-table.tsx
Resolves https://github.com/trustification/trustify-ui/issues/395
If the table contains a link to another page then we should not truncate the column as tooltips won't popup. We should render the whole word instead even if it increases the vertical size of the row.
> :sparkles: apply breakword to long names on main table column

- client/rsbuild.config.ts
- client/src/app/components/VulnerabilityGallery.tsx
RSBuild does not do deep checking by default. See docs here https://rsbuild.dev/guide/basic/typescript#type-checking
- Checking types at buildtime will help us identify errors like the `client/src/app/components/VulnerabilityGallery.tsx` change this PR includes
- This PR enables it only to `npm run build` and not to `npm run start:dev`.
- I played with enabling it for dev mode and it becomes annoying the compiler to keep throwing errors when you are create big chunks of code as of course there is gonna be plenty of code that might contain minor breaking rules. 
- Leaving things as they are for dev mode and only enforcing to building will help us IMO
> :seedling:  Introduce TS Checking on building

- client/src/app/pages/package-details/sboms-by-package.tsx
Originally requested by https://issues.redhat.com/browse/TC-2203
The SBOMs using Package Table should be sorted alphabetically by default.
Waiting for https://github.com/trustification/trustify/issues/1476 to be solved
> :sparkles: [TC-2203] add sorting to SBOMs using package table

- client/src/app/pages/home/components/MonitoringSection.tsx
https://issues.redhat.com/browse/TC-2374
- Add a Link to the advisory name to allow navigation
- Switch `advisories?.[0]?.identifier` by `advisories?.[0]?.document_id` as `document_id` is what we are using in the Advisory List Page and also because `advisories?.[0]?.identifier` can sometimes contain values as a URL which is not what we want to render
> :bug: [TC-2374] dashboard - add advisory link

- client/src/app/hooks/domain-controls/useSbomsOfVulnerability.ts
- client/src/app/hooks/domain-controls/useVulnerabilitiesOfPackage.ts
- client/src/app/hooks/domain-controls/useVulnerabilitiesOfSbom.ts
- client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
Depends on https://github.com/trustification/trustify-ui/pull/436
https://issues.redhat.com/browse/TC-2390
In the Vulnerability - Sboms table:
-  Fix the total count of dependencies
- When the user clicks in the total count of dependencies, there were duplicate packages being rendered so with this PR also the expanded area should render unique packages.
> :bug: [TC-2390] fix vulnerability-sboms table count of dependencies & render unique dependencies

- branding/strings.json
- client/src/app/layout/header.tsx
- client/src/app/layout/sidebar.tsx
- common/src/branding-strings-stub.json
- common/src/branding.ts
- common/src/proxies.ts
For v1 compatibility this PR adds:
- A new menu on the left siderbar that points to Swagger UI
- In the Masterhead, there is going to be a new button named "support" which should contain an external URL
> :sparkles: Add support & openapi links

- client/src/app/pages/advisory-details/vulnerabilities-by-advisory.tsx
- client/src/app/pages/advisory-list/advisory-list.tsx
- client/src/app/pages/advisory-list/advisory-table.tsx
- client/src/app/pages/advisory-list/advisory-toolbar.tsx
- client/src/app/pages/importer-list/importer-list.tsx
- client/src/app/pages/package-details/sboms-by-package.tsx
- client/src/app/pages/package-details/vulnerabilities-by-package.tsx
- client/src/app/pages/package-list/package-list.tsx
- client/src/app/pages/package-list/package-table.tsx
- client/src/app/pages/package-list/package-toolbar.tsx
- client/src/app/pages/sbom-details/packages-by-sbom.tsx
- client/src/app/pages/sbom-details/vulnerabilities-by-sbom.tsx
- client/src/app/pages/sbom-list/sbom-list.tsx
- client/src/app/pages/sbom-list/sbom-table.tsx
- client/src/app/pages/sbom-list/sbom-toolbar.tsx
- client/src/app/pages/search/components/SearchTabs.tsx
- client/src/app/pages/vulnerability-details/advisories-by-vulnerability.tsx
- client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
- client/src/app/pages/vulnerability-list/vulnerability-list.tsx
- client/src/app/pages/vulnerability-list/vulnerability-table.tsx
- client/src/app/pages/vulnerability-list/vulnerability-toolbar.tsx
- Now all tables within the Search page should have pagination on top of the table.
- Also all paginations in the bottom do not have the COMPACT variant any more as requested at https://issues.redhat.com/browse/TC-2348
> :sparkles: add top pagination to tables in search page & disable compact pagination on bottom tables

- client/src/app/components/SbomVulnerabilitiesDonutChart.tsx
The Donut Chart in the Dashboard page has the legends starting from Low to Critical (top to bottom) but it should be the opposite. This PR reverses the order of legends
Before
After
> :bug: fix Donut Chart Legend Order

- client/src/app/pages/importer-list/importer-list.tsx
https://issues.redhat.com/browse/TC-2397
An Importer can have only 3 statuses:
- "disabled"
- "scheduled" -> means it is enabled but waiting to be executed
- "running"
This will allow the RUN action to appear only when the Importer is scheduled but disappear when the Importer is either running or disabled
> :bug: [TC-2397] Run should only appear if importer is scheduled

- client/src/app/api/rest.ts
- client/src/app/pages/upload/components/upload-file.tsx
https://issues.redhat.com/browse/TC-2435
Files with the extension .gz cannot be uploaded since they are not supported by the backend yet. 
This PR avoids mentioning .gz files in the Upload Page
> :sparkles: [TC-2435] avoid uploading .gz files

- client/src/app/components/LoadingWrapper.tsx
- client/src/app/components/TableCellError.tsx
- client/src/app/pages/package-list/components/PackageVulnerabilities.tsx
- client/src/app/pages/sbom-list/components/SbomVulnerabilities.tsx
- client/src/app/pages/vulnerability-list/components/SbomsCount.tsx
https://issues.redhat.com/browse/TC-2434
Currently, tables like the SBOM List table fetches data for counting Vulnerabilities and render it under the Vulnerabilities Column. When there is an error (like timeout error) we only render the word `Error` wrapped in a Red Label.
With this PR we will also render the Error Code. E.g. `500 Error` so at least the it is more clear what type of error was generated.
> :sparkles: [TC-2434] Add TableCellError component

- .github/workflows/pr-closed.yaml
The release-tools repository renamed the workflow `cherry-pick.yaml` by `backport.yaml` so we align the change in this PR
> :seedling: align cherry-pick action with release-tools

- client/src/app/components/TableCellError.tsx
Currently the TableCellError component renders a string rather than the numeric error code.
This PR should make sure it is the numeric error code what is being rendered.
> :bug: TableCellError should render numeric error

- client/src/app/pages/advisory-details/vulnerabilities-by-advisory.tsx
- client/src/app/pages/advisory-list/advisory-table.tsx
- client/src/stories/v2.1/pages/search.tsx
- client/src/stories/v2.1/product-list.stories.tsx
https://github.com/trustification/trustify-ui/pull/478 Evidenced that in the component client/src/app/pages/advisory-details/vulnerabilities-by-advisory.tsx the `score` can be a null value. 
This PR makes sure client/src/app/pages/advisory-details/vulnerabilities-by-advisory.tsx passes a possible null score and makes sure the severity is converted to `ExtendedSeverity` before it is being passed to the `SeverityShieldAndText` component.
Also removes some warnings from the storybook fields.
> :bug: align Severity & Score nullable fields

- .github/workflows/ci-repo.yaml
To my understanding the UI CI already creates coverage data. This PR should upload those to the codecov.io as well.
> ci: add upload of coverage data

- .github/workflows/image-build.yaml
- .github/workflows/issues.yaml
- .github/workflows/pr-closed.yaml
- CONTRIBUTING.md
This PR moves all old references from `trustification/release-tools` to `guacsec/trustify-release-tools`
> ci: reference trustify-release-tools

- .env
- .github/workflows/ci-e2e.yaml
As we moved from the old Github Organization "Trustification" to "Guacsec" we also need to migrate our references of container images
> ci: move container organization owner
