client/src/app/api/models.ts
client/src/app/pages/importer-list/components/importer-form.tsx
client/src/app/pages/importer-list/importer-list.tsx

Fixes: https://github.com/trustification/trustify-ui/issues/38

Align importers to latest backend status

---

client/src/index.tsx

This is a small update to align with React 18 approach : https://react.dev/blog/2022/03/08/react-18-upgrade-guide#updates-to-client-rendering-apis

React 18: Update client rendering

---

client/src/app/api/rest.ts

Removes unnecessary call on the stack.
Definitely not a big deal and although it looks more tidy it's not just about cosmetic.

Avoid to use stack when not needed

---

client/src/app/api/models.ts
client/src/app/pages/advisory-list/advisory-list.tsx
client/src/app/pages/vulnerability-details/related-advisories.tsx
client/src/mocks/stub-new-work/advisories.ts

To be aligned with the changes made at https://github.com/trustification/trustify/pull/380

Use Advisory uuid as identifier

---

client/src/app/pages/advisory-details/overview.tsx

Removing label as https://github.com/trustification/trustify/issues/279 was closed

Remove the ISSUE-279 label as it was closed

---

client/src/app/Constants.ts
client/src/app/api/models.ts
client/src/app/api/rest.ts
client/src/app/components/PackageQualifiers.tsx
client/src/app/pages/sbom-details/packages.tsx
client/src/app/utils/utils.ts

Issues created on the backend:
- https://github.com/trustification/trustify/issues/434
- https://github.com/trustification/trustify/issues/435

Add SBOM's packages table view

---

client/src/app/api/models.ts
client/src/app/api/rest.ts
client/src/app/pages/advisory-details/vulnerabilities.tsx
client/src/app/pages/package-details/package-details.tsx
client/src/app/pages/package-details/related-cves.tsx
client/src/app/pages/package-list/package-list.tsx
client/src/app/pages/sbom-details/cves.tsx
client/src/app/pages/sbom-details/packages.tsx
client/src/app/pages/sbom-list/components/packages-count.tsx
client/src/app/pages/vulnerability-details/related-advisories.tsx
client/src/app/pages/vulnerability-details/related-sboms.tsx
client/src/app/queries/packages.ts
client/src/app/queries/sboms.ts
client/src/app/queries/vulnerabilities.ts
client/src/app/utils/utils.ts

No functional change, only refactoring code:
- Rename some models to be more verbose
- Move some query functions to their appropriate files
- Order some rest functions within the same file

task: refactor model namings and query locations

---

client/src/app/hooks/table-controls/filtering/getFilterHubRequestParams.ts

Fixes https://github.com/trustification/trustify-ui/issues/74

fix: do not include empty filter values

---

client/src/app/pages/package-list/package-list.tsx

fixes https://github.com/trustification/trustify-ui/issues/64

Package list: Set qualifiers on main row

---

client/src/app/Constants.ts
client/src/app/api/models.ts
client/src/app/api/rest.ts
client/src/app/components/IconedStatus.tsx
client/src/app/pages/importer-list/importer-list.tsx
client/src/app/queries/importers.ts
client/src/app/utils/utils.ts

Fixes: https://github.com/trustification/trustify-ui/issues/69 , https://github.com/trustification/trustify-ui/issues/72 , https://github.com/trustification/trustify-ui/issues/49

feat: enhance importers rendering

---

client/src/app/api/rest.ts

Changes done in https://github.com/trustification/trustify/pull/468

Update package url path changes

---

client/src/app/api/rest.ts
client/src/app/pages/importer-list/importer-list.tsx

Fixes: https://github.com/trustification/trustify-ui/issues/106
Adding:
- Run and Enable/Disable actions for the importers

Add importer additional actions

---

client/src/app/components/TableControls/TableHeaderContentWithControls.tsx
client/src/app/pages/importer-list/components/importer-form.tsx
client/src/app/pages/sbom-list/sbom-list.tsx

Fix https://github.com/trustification/trustify-ui/issues/96

fix: Add aria-label to some <Th>

---

client/src/app/Constants.ts
client/src/app/Routes.tsx
client/src/app/api/models.ts
client/src/app/api/rest.ts
client/src/app/layout/sidebar.tsx
client/src/app/pages/product-details/index.ts
client/src/app/pages/product-details/overview.tsx
client/src/app/pages/product-details/product-details.tsx
client/src/app/pages/product-details/product-versions.tsx
client/src/app/pages/product-list/index.ts
client/src/app/pages/product-list/product-list.tsx
client/src/app/pages/sbom-details/packages-by-sbom.tsx
client/src/app/pages/vulnerability-details/packages-by-vulnerability.tsx
client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
client/src/app/queries/organizations.ts
client/src/app/queries/products.ts

Changes:
- Introduces the Products List sidebar/page
- Introduces the Product Details page
- Chance models accordingly as a consequence of https://github.com/trustification/trustify/pull/537 being merged

feat: Add products

---

client/src/app/api/models.ts
client/src/app/components/AdvisoryGeneralView.tsx
client/src/app/components/AdvisoryInDrawerInfo.tsx
client/src/app/components/AdvisoryIssuer.tsx
client/src/app/components/PackageInDrawerInfo.tsx
client/src/app/pages/advisory-details/overview.tsx
client/src/app/pages/advisory-details/vulnerabilities.tsx
client/src/app/pages/advisory-list/advisory-list.tsx
client/src/app/pages/package-details/sboms-by-package.tsx
client/src/app/pages/package-details/vulnerabilities-by-package.tsx
client/src/app/pages/package-list/package-list.tsx
client/src/app/pages/product-details/product-versions.tsx
client/src/app/pages/sbom-details/overview.tsx
client/src/app/pages/sbom-details/sbom-details.tsx
client/src/app/pages/vulnerability-details/advisories-by-vulnerability.tsx
client/src/app/pages/vulnerability-details/packages-by-vulnerability.tsx
client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx

- Align models based on https://github.com/trustification/trustify/pull/550 and the openapi exposed in the backend
- Add "Context" column when it comes to explain "package -vulnerability" & "vulnerability- package"
To quickly test this PR you can upload this advisory:
[rhsa-2024-2705.json](https://github.com/user-attachments/files/16286777/rhsa-2024-2705.json)
And the upload these SBOMs
[quarkus-bom-3.2.12.Final-redhat-00002.json](https://github.com/user-attachments/files/16286782/quarkus-bom-3.2.12.Final-redhat-00002.json)
[quarkus-bom-3.2.11.Final-redhat-00001.json](https://github.com/user-attachments/files/16286783/quarkus-bom-3.2.11.Final-redhat-00001.json)

Align changes to backend

---

client/openapi/trustd.yaml
client/src/app/client/schemas.gen.ts
client/src/app/client/services.gen.ts
client/src/app/client/types.gen.ts
client/src/app/hooks/useNotifyErrorCallback.ts
client/src/app/pages/advisory-list/advisory-list.tsx
client/src/app/pages/product-list/product-list.tsx
client/src/app/pages/sbom-list/sbom-list.tsx
client/src/app/pages/vulnerability-list/vulnerability-list.tsx
client/src/app/queries/advisories.ts
client/src/app/queries/products.ts
client/src/app/queries/sboms.ts
client/src/app/queries/vulnerabilities.ts

Added to:
* Vulnerabilities
* Products
* Advisories.
* SBOMs
Task of https://github.com/trustification/trustify/issues/563

feat: Add menu items that allows deleting resources.

---

client/openapi/trustd.yaml
client/src/app/client/schemas.gen.ts
client/src/app/client/types.gen.ts
client/src/app/pages/package-details/vulnerabilities-by-package.tsx
client/src/app/pages/sbom-details/vulnerabilities-by-sbom.tsx
client/src/app/pages/vulnerability-details/advisories-by-vulnerability.tsx
client/src/app/pages/vulnerability-details/overview.tsx
client/src/app/pages/vulnerability-details/packages-by-vulnerability.tsx
client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
client/src/app/queries/dataOf.ts
client/src/app/queries/sboms.ts
client/src/app/queries/vulnerabilities.ts

Added a convertQuery function that converts the results of the queries to that expected type by the pages.

Migrate `queries/vulnerabilities.ts` to use `@app/client`

---

client/package.json
client/src/app/api/model-utils.ts
client/src/app/components/SeverityShieldAndText.tsx
client/src/app/components/SimplePagination/SimplePagination.tsx
client/src/app/pages/sbom-details/overview.tsx
client/src/app/pages/sbom-details/packages-by-sbom.tsx
client/src/app/pages/sbom-details/sbom-details.tsx
client/src/app/pages/sbom-details/vulnerabilities-by-sbom.tsx
package-lock.json

Fixes https://github.com/trustification/trustify-ui/issues/200
The images below represent how the Details page will look like.
I couldn't find valid SBOMs and Advisories to be uploaded and then be able to visualize SBOM Vulnerabilities but that should not block the review of this PR.

SBOM Details Page V1 parity

---

client/src/app/pages/sbom-list/sbom-context.tsx

feat: sbom-list table add sort by "name"

---

client/src/app/pages/vulnerability-list/vulnerability-context.tsx
client/src/app/pages/vulnerability-list/vulnerability-list.tsx
client/src/app/pages/vulnerability-list/vulnerability-table.tsx

Relates to #172 
Still missing a few things like sorting by CVSS and Date published, figuring out what Related documents is (maybe the `length` of SBOMs?), and maybe finding data to show CVSS column, but it's slowly coming together.

chore(cve): cve list v1 parity enhancements

---

client/src/app/pages/package-details/package-details.tsx
client/src/app/pages/sbom-details/overview.tsx
client/src/app/pages/sbom-list/sbom-table.tsx
client/src/app/pages/search/search.tsx
client/src/app/pages/vulnerability-details/advisories-by-vulnerability.stories.tsx
client/src/app/pages/vulnerability-details/advisories-by-vulnerability.tsx
client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx
client/src/app/pages/vulnerability-details/vulnerability-details.tsx

- Search Page:
- Change the title from `Search` to `Search Results` as it is the title in V2
- SBOM List page:
-  Remove the DELETE action button as V1 does not allow to delete SBOMs.
-  SBOM Details Page:
- Add more fields to the Info/Overview tab: Namespace, Statistics Card
- Package Details Page:
- Move the tabs that are under the Nav Section to be inside the top white section. This is not what V1 has but after talking with PM we need to have consistency on where the content of Tabs are located. The PM recommendation was to have consistency everywhere.
BEFORE:
AFTER:
- Vulnerabilities Details Page:
- Same change as the previous one. Move the Tabs to be inside the white Nab Section to have Consistency.
BEFORE:
AFTER:

task: general enhancements

---

client/src/app/oidc.ts

fixes: https://github.com/trustification/trustify-ui/issues/41

fix: oidc set redirect url to the root path of the app

---

client/src/app/axios-config/apiInit.ts

Fixes: https://github.com/trustification/trustify-ui/issues/246

fix: 401 responses =>retry only once

---

client/src/app/pages/sbom-details/vulnerabilities-by-sbom.tsx

In the image below see the expanded area of the "Affected dependencies" column. This PR will render the name of the package if no PURLs were found (By default we render PURLs).
There is some work being done at https://github.com/trustification/trustify/issues/1043 and https://github.com/trustification/trustify/pull/1014 but this should work meanwhile.

fix: sbom details-vulnerability tab-render "affected dependencies"

---

client/src/app/layout/sidebar.tsx
client/src/app/pages/advisory-details/overview.tsx
client/src/app/pages/advisory-details/vulnerabilities-by-advisory.tsx
client/src/app/pages/home/components/MonitoringSection.tsx
client/src/app/pages/importer-list/importer-list.tsx
client/src/app/pages/search/components/SearchMenu.tsx
client/src/app/pages/search/components/SearchTabs.tsx
client/src/app/pages/vulnerability-details/index.ts
client/src/app/pages/vulnerability-details/vulnerability-details.stories.tsx
client/src/app/pages/vulnerability-details/vulnerability-details.tsx
client/src/app/pages/vulnerability-list/vulnerability-list.tsx

Agreed with PM and Backend guys folks that the term "CVE" is misleading even if that is what we used in V1. It was recommended to use "Vulnerability" wording as that is more aligned to the new mental model and design of V2

fix: replace "CVE" wording by "Vulnerability"

---

.github/workflows/ci-repo.yaml
client/src/app/pages/package-list/package-context.tsx

In response to https://github.com/trustification/trustify/pull/1073

feat: package list page - sorting

---

client/src/app/oidc.ts

Fixes: https://github.com/trustification/trustify-ui/issues/279

fix: links opened in new tabs should not redirect to base path

---

client/src/app/hooks/domain-controls/useVulnerabilitiesOfPackage.ts
client/src/app/pages/package-details/vulnerabilities-by-package.tsx
client/src/app/pages/package-list/components/PackageVulnerabilities.tsx

The backend was enhanced to provide the Vulnerability severity when we fetch a package at https://github.com/trustification/trustify/pull/1128
This PR will make fetching a package enough to get all the data the UI needs

fix: package's vulnerabilities -> reduce number of calls

---

client/openapi/trustd.yaml

Update trustify openapi definition

:sparkles: update client/openapi/trustd.yaml

---

client/src/app/pages/vulnerability-list/vulnerability-context.tsx

Fixes: https://github.com/trustification/trustify-ui/issues/350

:sparkles: Rename column "related documents" by "impacted sboms" => table: SBOM/Vulnerability

---

client/package.json
package-lock.json

Fixes: https://github.com/trustification/trustify-ui/issues/278
The current patternfly-react dependency is affected by https://github.com/patternfly/patternfly-react/issues/10857 whose fix has been implemented by https://github.com/patternfly/patternfly-react/pull/11223

:seedling: Upgrade @patternfly/react-core

---

client/src/app/pages/sbom-list/sbom-context.tsx

Temporary Performance fix until a final decision on regards of https://github.com/trustification/trustify-ui/issues/116 is taken

:sparkles: SBOM Table: remove default sort by creation-date

---

client/src/app/pages/home/components/MonitoringSection.tsx
client/src/app/pages/home/components/WatchedSbom.tsx

Resolves https://github.com/trustification/trustify-ui/issues/404

:bug: Dashboard does not load data

---

client/src/app/components/OidcProvider.tsx
client/src/app/oidc.ts

Resolves https://github.com/trustification/trustify-ui/issues/41 and https://github.com/trustification/trustify-ui/issues/353
To test this PR we only need to setup cognito or keycloak and the setup to redirect url to http://localhost:3000 and make sure we can do the auth flow + verify the issues mentioned above are fixed.

:bug: redirect_url should be the rootPath

---

client/src/app/pages/advisory-details/advisory-details.tsx
client/src/app/pages/advisory-list/advisory-context.tsx
client/src/app/pages/advisory-list/advisory-table.tsx
client/src/app/pages/vulnerability-details/advisories-by-vulnerability.tsx

Resolves https://issues.redhat.com/browse/TC-2211
As suggested in the JIRA ticket we need to add the advisory type that lies as a Label under the name of "type"

:sparkles: Add Advisory type

---

client/src/app/pages/advisory-details/vulnerabilities-by-advisory.tsx

Originally requested by https://issues.redhat.com/browse/TC-2199

:bug: Rename Advisory Vulnerability Score Column Header

---

client/src/app/layout/about.tsx

Changing About Modal Text. The Same as in V1

:sparkles: About Modal: V1 compatibility text

---

client/src/app/components/SeverityShieldAndText.tsx

https://issues.redhat.com/browse/TC-2398

:sparkles: [TC-2398] Round score to 1 digit

---

client/src/app/pages/package-details/sboms-by-package.tsx
client/src/app/pages/sbom-details/overview.tsx
client/src/app/pages/sbom-list/sbom-table.tsx
client/src/app/pages/search/components/SearchMenu.tsx
client/src/app/pages/vulnerability-details/sboms-by-vulnerability.tsx

https://issues.redhat.com/browse/TC-2372

:sparkles: [TC-2372] use sbom's supplier rather than authors

---

client/src/app/pages/sbom-details/packages-by-sbom.tsx

https://issues.redhat.com/browse/TC-2320
Adds the list of CPEs below the list of PURLs

:sparkles: [TC-2320] add CPEs to SBOM's packages table

---

client/src/app/pages/home/components/WatchedSbom.tsx

https://issues.redhat.com/browse/TC-2419

:sparkles: [TC-2419] Dashboard dropdown - apply sort

---

client/src/app/pages/search/components/SearchMenu.tsx

https://issues.redhat.com/browse/TC-2401

:sparkles: [TC-2401] Search Page - input search should watch table input search filter

---

client/src/app/pages/advisory-details/overview.tsx
client/src/app/pages/advisory-list/advisory-context.tsx
client/src/app/pages/advisory-list/advisory-table.tsx
client/src/app/pages/vulnerability-details/advisories-by-vulnerability.tsx

https://issues.redhat.com/browse/TC-2605
This PR removes the AverageSeverity of Advisories as requested and agreed in the JIRA linked in the top of this JIRA.
cc: @dejanb

:sparkles: [TC-2605] remove aggregated severity from Advisories

---

client/src/app/App.css
client/src/app/pages/upload/components/upload-file.tsx

https://issues.redhat.com/browse/TC-2525

:bug: [TC-2525] remove upload progress bar colors done by css

---

client/src/app/components/TableControls/ConditionalTableBody.tsx
client/src/app/pages/sbom-details/packages-by-sbom.tsx
client/src/app/pages/sbom-list/sbom-toolbar.tsx
client/src/app/pages/vulnerability-list/vulnerability-toolbar.tsx

Add aria labels for helping with identifiers

:ghost: add aria labels

---

client/src/app/components/Autocomplete/Autocomplete.tsx
client/src/app/components/Autocomplete/useAutocompleteHandlers.ts

Make sure the selection is disabled after clicking a select option.
Fix https://issues.redhat.com/browse/TC-2661

Labels : Fix create new label

---

e2e/tests/ui/features/@advisory-explorer/advisory-explorer.feature
e2e/tests/ui/features/@advisory-explorer/advisory-explorer.step.ts
e2e/tests/ui/helpers/DetailsPage.ts
e2e/tests/ui/steps/details-page.ts

A set of tests that test basic Advisory Explorer UI functionality, migrated from the trustify-tests repository.

tests: Add Advisory UI tests

---

.github/workflows/ci-coverage.yaml
.github/workflows/ci-e2e-template.yaml

Backport of https://github.com/guacsec/trustify-ui/pull/693

👻 Bump actions/checkout from 4 to 5 [Backport release/0.3.z]
